version: '3.9'
services:
  nodedb:
    build: .
    ports:
      - "3000:3000"
    links:
      - mysqlDB
    volumes:
      - .:/home/nodePrueba
  mysqlDB:
    image: mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456789
    volumes:
      - baseprueba_mysql-data:/var/lib/mysql
volumes:
  baseprueba_mysql-data:
    external: true